'use client';

import {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type ReactElement,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { cn } from '@/lib/cn';

/* A KEYBOARD SHORTCUT IS TAUGHT HERE, NEVER BY `title`.
 *
 * The native attribute looks like it does this job and does not: it waits about a second before
 * appearing, never fires on keyboard focus at all, and cannot be styled. As a teaching device it
 * reaches exactly one person, the one already hovering and waiting to find out, while the people
 * most likely to want a shortcut are the ones driving by keyboard. This opens on hover AND on
 * focus, which is the whole point.
 *
 * IT RENDERS IN A PORTAL, and that is not over-engineering. The first version rendered in place and
 * was clipped in half by the sidebar's own `overflow-hidden` — which the sidebar needs, so its
 * contents do not spill out while the panel animates to zero width. Any absolutely-positioned thing
 * inside a clipping ancestor has this problem, and the only general fix is to leave the subtree.
 * A tooltip on a shell control is exactly the case that hits it.
 *
 * POSITION IS CLAMPED TO THE VIEWPORT rather than exposed as an `align` prop. The earlier version
 * had one, and it pushed the decision onto every call site: whoever adds a control near an edge has
 * to notice, and will not. Clamping is the same fix applied once, and it also handles the case the
 * prop could not — a window narrow enough that a centred tooltip overflows on both sides.
 * It flips above the trigger when there is no room below.
 *
 * The label first, then the key one ink-step quieter, so the pairing reads as "this control, and
 * this is how you reach it" rather than as two facts.
 */

const GAP = 8; // between trigger and tooltip
const EDGE = 8; // minimum breathing room against the viewport

/* HOVER WAITS, FOCUS DOES NOT, AND THE SECOND ONE IN A ROW DOES NEITHER.
 *
 * Opening instantly on hover means crossing a toolbar pops a tooltip at every icon the cursor
 * passes over, which is noise generated by a mouse in transit rather than by anyone asking a
 * question. A short wait filters that: it costs nothing to someone who actually paused, and it
 * makes a pass-through silent. The sidebar rail and the icon-button rows are exactly this case.
 *
 * FOCUS IS EXEMPT, and this does not come from the article - it follows from the reason for the
 * delay. There is no such thing as tabbing to a control by accident, so the noise the delay exists
 * to suppress cannot happen via keyboard. Delaying there would only slow down the users this
 * component was built for.
 *
 * ONCE ONE HAS BEEN SEEN, THE NEXT IS INSTANT AND UNANIMATED. Having answered the "what is this"
 * question once, the user is now reading along a row, and re-imposing the wait at every stop reads
 * as the interface lagging. The skip window is deliberately short, so it covers moving along a
 * group and expires by the time someone returns later with a fresh question.
 *
 * `lastShownAt` IS MODULE STATE ON PURPOSE. The skip has to be shared across sibling tooltips that
 * know nothing about each other, and the alternative is a context provider every call site has to
 * remember to wrap - a setup step whose only symptom when forgotten is a subtly worse feel, which
 * is the kind of thing nobody ever notices is missing. */
const OPEN_DELAY = 400;
const SKIP_WINDOW = 300;
let lastShownAt = 0;

export function Tooltip({
  label,
  shortcut,
  children,
}: {
  label: string;
  shortcut?: string;
  children: ReactNode;
}) {
  const id = useId();
  const anchor = useRef<HTMLSpanElement>(null);
  const tip = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);
  // True from the moment OPEN_DELAY starts counting until it fires or is cancelled. Exists so
  // Escape and scroll can cancel a tooltip that has been TRIGGERED but has not appeared yet -
  // without it those listeners were gated on `open` alone and a dismissal during the delay window
  // did nothing, so the tooltip still popped up after you had already tried to get rid of it.
  const [waiting, setWaiting] = useState(false);
  // Skips the fade as well as the wait: chaining along a row, an element that fades in at every
  // stop reads as slower than one that is simply already there.
  const [instant, setInstant] = useState(false);
  const [coords, setCoords] = useState<{ top: number; left: number } | null>(null);
  const [mounted, setMounted] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // createPortal needs a DOM target, which does not exist during the server render.
  useEffect(() => setMounted(true), []);

  const clearTimer = useCallback(() => {
    if (timer.current) {
      clearTimeout(timer.current);
      timer.current = null;
    }
  }, []);

  const show = useCallback(
    (immediate: boolean) => {
      clearTimer();
      // Chaining from a tooltip that was open moments ago, or arriving by keyboard: no wait.
      if (immediate || Date.now() - lastShownAt < SKIP_WINDOW) {
        setInstant(!immediate);
        setWaiting(false);
        setOpen(true);
        return;
      }
      setInstant(false);
      setWaiting(true);
      timer.current = setTimeout(() => {
        setWaiting(false);
        setOpen(true);
      }, OPEN_DELAY);
    },
    [clearTimer]
  );

  const hide = useCallback(() => {
    clearTimer();
    setWaiting(false);
    // Only a tooltip that was actually SHOWN starts the skip window. A cursor that passed over a
    // trigger without ever waiting out the delay has taught the user nothing, so it must not buy
    // the next one an instant open.
    //
    // Written HERE, synchronously, rather than inside the setOpen updater below. `open` is read
    // directly from the closure, which `hide` re-captures on every render because it is a
    // dependency - a plain assignment, so it lands before the sibling pointerover on an adjacent
    // trigger reads it. The updater version raced this: hopping straight from one tooltip to the
    // next fires leave-then-enter in the same batched tick, so `show()`'s synchronous read always
    // saw the value from BEFORE the updater had run, and the "no wait, no fade" chain never
    // actually triggered despite the timestamp looking right a moment later.
    if (open) lastShownAt = Date.now();
    setOpen(false);
  }, [clearTimer, open]);

  // A pending timer outliving its component fires setOpen on an unmounted tree. Reachable in
  // normal use: the sidebar unmounts its tooltipped controls as it collapses, which can easily
  // happen while the cursor is still over one of them.
  useEffect(() => clearTimer, [clearTimer]);

  const place = useCallback(() => {
    const a = anchor.current;
    const t = tip.current;
    if (!a || !t) return;

    const ar = a.getBoundingClientRect();
    const tr = t.getBoundingClientRect();

    let top = ar.bottom + GAP;
    if (top + tr.height > window.innerHeight - EDGE) top = ar.top - tr.height - GAP;

    const centred = ar.left + ar.width / 2 - tr.width / 2;
    const left = Math.max(EDGE, Math.min(centred, window.innerWidth - tr.width - EDGE));

    setCoords({ top, left });
  }, []);

  // Layout effect, not effect: measure and place before the browser paints, so the tooltip never
  // shows for a frame at the wrong coordinates.
  useLayoutEffect(() => {
    if (open) place();
    else setCoords(null);
  }, [open, place]);

  // Gated on open-OR-waiting, not open alone, so Escape and scroll can also kill a tooltip that
  // was triggered but has not appeared yet - dismissing during the delay window used to do
  // nothing, and the tooltip would still pop up after the user had already tried to get rid of it.
  useEffect(() => {
    if (!open && !waiting) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') hide();
    };
    // Capture phase: a scroll in ANY ancestor pane moves the trigger out from under a fixed
    // tooltip, and scroll events from a nested scroller do not bubble to window.
    window.addEventListener('scroll', hide, true);
    window.addEventListener('resize', hide);
    document.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('scroll', hide, true);
      window.removeEventListener('resize', hide);
      document.removeEventListener('keydown', onKey);
    };
  }, [open, waiting, hide]);

  // The description belongs on the CONTROL, not on the wrapper, or a screen reader announces the
  // shortcut for whatever happens to be focused inside instead of for the button itself.
  const trigger = isValidElement(children)
    ? cloneElement(children as ReactElement<{ 'aria-describedby'?: string }>, {
        'aria-describedby': id,
      })
    : children;

  return (
    <>
      <span
        ref={anchor}
        className="inline-flex"
        onPointerEnter={() => show(false)}
        onPointerLeave={hide}
        // onFocus/onBlur are delegated from focusin/focusout in React, so they fire for the control
        // inside rather than only for this wrapper.
        onFocus={() => show(true)}
        onBlur={hide}
      >
        {trigger}
      </span>

      {mounted &&
        open &&
        createPortal(
          <div
            ref={tip}
            id={id}
            role="tooltip"
            style={coords ?? undefined}
            className={cn(
              'bg-elevated border-border text-small text-text pointer-events-none fixed z-50',
              'rounded-sm border px-3 py-2 whitespace-nowrap',
              // ease-out: a tooltip ENTERS and LEAVES, so it takes the entrance curve rather
              // than the project's `ease` default, which is for a state change in place.
              instant ? 'transition-none' : 'transition-opacity ease-out',
              // Placed on the first layout pass; until then it has no coordinates and must not be
              // visible anywhere.
              coords ? 'opacity-100' : 'opacity-0'
            )}
          >
            {label}
            {shortcut && <kbd className="text-caption text-muted ml-3 font-sans">{shortcut}</kbd>}
          </div>,
          document.body
        )}
    </>
  );
}
